export const CONTACT_EMAIL = 'aishopyapp@gmail.com'
export const COMPANY_NAME = 'BaytCode Technologies Pvt Ltd'
export const STOREFRONT_DOMAIN = 'AiShopy.io'
export const PRIVACY_URL = 'https://www.aishopy.io/privacy'
export const TERMS_URL = 'https://www.aishopy.io/terms'
export const PLAY_STORE_URL =
  'https://play.google.com/store/apps/details?id=com.aishopy.app'
export const APP_STORE_URL = 'https://apps.apple.com/in/app/aishopy/id6802297718'
export const WEB_APP_URL = 'https://app.aishopy.io'
export const WEB_APP_LOGIN_URL = `${WEB_APP_URL}/login`
